name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "24"
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          registry-url: https://registry.npmjs.org
      - name: Install deps
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: publish
        run: pnpm -r publish --no-git-checks --access=public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.POLKAHUB_PUBLISH_AUTOMATION_TOKEN }}
          NPM_CONFIG_PROVENANCE: "true"
